### ISSUE TITLE
SSL Verify with custom CA certs

### ISSUE THREAD

**Issue by sud0nick** [bhoriuchi/passport-activedirectory#10]
I'm using passport-activedirectory inside a docker container and binding to a domain controller that has certs from an in-house CA.  I keep getting UNABLE_TO_GET_LOCAL_ISSUER_CERTIFICATE when a user tries to log in.  The CA chain exists on the docker host at /etc/pki/tls/certs/ca-bundle and I've also tried adding them directly to the container using a volume.  Could you tell me where this module is looking for CA certs so I can place them in the proper directory?

**Comment by bhoriuchi** [comment]
this module uses the ActiveDirectory module which itself uses the ldapjs module. In the documentation there you should set the "tlsOptions". I have not tested this but it should potentially look like

```js
passport.Use(new ActiveDirectoryStrategy({
  ldap: {
    // ... normal ldap settings
    tlsOptions: {
      ca: [fs.readFileSync('path-to-ca-cert.pem')]
    }
  }
}))
```

**Comment by combsn** [comment]
Thanks for the quick response!  I'll give that a shot tomorrow and let you know how it goes.

**Comment by sud0nick** [comment]
Thanks for the quick response! I'll give that a shot tomorrow and let you know how it goes.

**Comment by sud0nick** [comment]
This worked perfectly!  Thank you very much!
