### ISSUE TITLE
How to use filter ?

### ISSUE THREAD

**Issue by ericrv01** [bhoriuchi/passport-activedirectory#15]
Hello,

I'm able to define a strategy and authenticate my users.
I would like to filter the search for certains groups like that for instance :

filter: '(&(objectClass=group)(|(CN=GRP_1)(CN=GRP_2)(CN=GRP_3)))'

but I'm not able to make it work, I continue to find users even they are not member of the group.

Any idea ?

Thanks

**Comment by bhoriuchi** [comment]
this is a question about LDAP filters of which I am not a subject matter expert. The package that performs interaction with AD is https://www.npmjs.com/package/activedirectory2
