### ISSUE TITLE
InvalidCredentialsError should result in 401, not 500

### ISSUE THREAD

**Issue by LoneRifle** [bhoriuchi/passport-activedirectory#5]
When `integrated: false`, the auth callback in line 123 treats _all_ errors the same, ie 500. 

This includes `InvalidCredentialsError`, which really should be treated as an authentication failure, ie 401. 

Treating `InvalidCredentialsError` as auth failure is in-line with the spec written for strategies, as documented in https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L279 and https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L341.

**Comment by bhoriuchi** [comment]
PR's welcome
